### ISSUE TITLE
"Array buffer allocation failed" when finalizing with FileSystemWritableFileStreamTargetWriter

### ISSUE THREAD

**Issue by rawmahn** [Vanilagy/mp4-muxer#78]
Hi,

So I'm trying to export a large file (around 1.5GB), and using FileSystemWritableFileStreamTargetWriter, but it crashes right upon trying to call muxer.finalize(). 

```
mp4-muxer.mjs:714 Uncaught (in promise) RangeError: Array buffer allocation failed
    at new ArrayBuffer (<anonymous>)
    at new Uint8Array (<anonymous>)
    at FileSystemWritableFileStreamTargetWriter.createChunk_fn (mp4-muxer.mjs:714:1)
    at FileSystemWritableFileStreamTargetWriter.writeDataIntoChunks_fn (mp4-muxer.mjs:665:1)
    at FileSystemWritableFileStreamTargetWriter.writeDataIntoChunks_fn (mp4-muxer.mjs:685:1)
    at FileSystemWritableFileStreamTargetWriter.write (mp4-muxer.mjs:650:1)
    at Muxer.finalize (mp4-muxer.mjs:849:1)

```
Using the latest version 5.1.5, but it did the same in 3.x that I had in my proejct previously.

If this helps this is how I initialize the muxer:
```
this.muxer = new Muxer({
            fastStart: 'in-memory',
            target: new FileSystemWritableFileStreamTarget(stream),
            video: {
                codec: 'avc',
                width: this.w,
                height: this.h
            },
            audio: {
                codec: 'aac',
                sampleRate: this.audioSampleRate,
                numberOfChannels: this.audioNumberOfChannels
            },
            firstTimestampBehavior: 'offset'
        });
```

It works well while I keep adding the frames, but crashes upon "finalize". It works fine for smaller files.

Any help would be appreciated.

**Comment by Vanilagy** [comment]
Thanks for reporting this! Looking at my code, the method simply allocates a 16 MB buffer, so that alone cannot be the issue. Perhaps something can't get garbage collected and you're simply running out of memory for the large file, which is of course not something that should happen. Does this error occur for small files too?

Do you think you can provide me with a demo that creates such a large file or should I simply mess around and come up with something myself?

**Comment by kong303917** [comment]
I has the same issue.
When I used **StreamTarget** , the page crashed.
How can I fix it ?

**Comment by Vanilagy** [comment]
What is the error specifically?

**Comment by kong303917** [comment]
The page likes this.
![5edb29fb-2193-4346-b981-6b5bcb433cc9](https://github.com/user-attachments/assets/ba993fa6-fded-434c-998d-331d9161c047)

**Comment by Vanilagy** [comment]
I guess this is an out of memory error. I can't help you without further detail

**Comment by 0-mandrixx-0** [comment]
I have a similar issue when muxing large files (~2GB, 1h video) with ArrayBufferTarget
it stops after encoding 40 minutes of full hd video.

I have this error :
writer.ts:103 Uncaught (in promise) RangeError: Array buffer allocation failed
    at new ArrayBuffer (<anonymous>)
    at #ensureSize (writer.ts:103:19)
    at ArrayBufferTargetWriter.write (writer.ts:112:8)
    at #writeCurrentChunk (muxer.ts:362:65)
    at #addSampleToTrack (muxer.ts:280:33)
    at Muxer.addVideoChunkRaw (muxer.ts:241:8)
    at Muxer.addVideoChunk (muxer.ts:228:8)
    at MP4mux.addVideoChunk (MP4Mux.ts:67:22)
    
I have plenty of free ram on my computer and chrome is at around 3.5GB when the error occurs.

**Comment by Vanilagy** [comment]
Yes that is to be expected, a tab cannot use all your system memory. Don't use ArrayBufferTarget for such a large file!!

**Comment by 0-mandrixx-0** [comment]
Yes. there seem to be a limit of 4GB with chrome, for security reasons.
I have no other choice, filesystemapi is not available on iOS devices and the storage options are limited ^
Ty anyway !

**Comment by Vanilagy** [comment]
Maybe you can try hacking something together using IndexedDB, but may be hacky. Or something with OPFS?

**Comment by w17612745587** [comment]
> yes, I've implemented indexedDB and it's working fine, even with gigabytes of files stored. Another option is to use localstorage, but it requires base64 encoding/decoding. I can't find much info about this 4GB limitation, But it seems to be a per tab limit. I will try to find out why it's stopping at 2gb, there must be something else eating the memory.

I have a similar issue to yours , could you please show me your code about how does you fix the problem in indexedDB?

**Comment by rawmahn** [comment]
No, not really, large files like this are not a prio in my project anymore, so I walked away from the issue.. Thanks for help
